import {useState,useEffect} from "react"
import Head from 'next/head'

export default function profileUpdate() {
    const [screenHeight, setScreenHeight] = useState(0);

  useEffect(()=>{
    setScreenHeight(window.innerHeight - 60);
  },[])
  return (
    <>
        <Head>
            <title>Talent Profile Update | Real Fast</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container} style={{height:`${screenHeight}px`}}>
            <div className={styles.wrapper}>
                <h2 className={styles.title}>Update Your Profile</h2>

                <form action="">
                    <div className={styles.inputBlockRow}>
                        <div className={styles.inputBlock}>
                            <label className={styles.label} htmlFor="">First Name</label>
                            <input type="text" placeholder="first & middle name" className={styles.inputField} />
                        </div>
                        <div className={styles.inputBlock}>
                            <label className={styles.label} htmlFor="">Last Name</label>
                            <input type="text" placeholder="surname" className={styles.inputField} />
                        </div>
                    </div>
                    <div className={styles.inputBlock}>
                        <label className={styles.label} htmlFor="">PhoneNumber</label>
                        <input type="tell" placeholder="phone number" className={styles.inputField} />
                        <label className={styles.label} htmlFor="">Address</label>
                        <input type="text" placeholder="contact address" className={styles.inputField} />
                    </div>

                    <div className={styles.inputBlockRow}>
                        <div className={styles.inputBlock}>
                            <label className={styles.label} htmlFor="">Date of Birth</label>
                            <input type="date" className={styles.inputField} />
                        </div>
                        <div className={styles.inputBlock}>
                            <label className={styles.label} htmlFor="">Gender</label>
                            <select className={styles.inputField}>
                                <option value="Not Specified">Not Specified</option>
                                <option value="Female">Female</option>
                                <option value="Male">Male</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>

            
        </main>
    </>
  )
}

const styles={
  container:'w-full flex flex-col justify-center items-center px-16',
  wrapper:'md:w-full  flex flex-col gap-16',
  title:'text-xl text-center',
  inputBlockRow:'w-full flex flex-col md:flex-row md:space-x-3',
  inputBlock:'w-full',
  label:'font-bold md:mb-3',
  inputField:'w-full border-2 border-gray-400 py-3 px-4 rounded',
}