import {useState,useEffect} from "react"
import Head from 'next/head'
import Link from "next/link";

export default function Jobs() {
    const [screenHeight, setScreenHeight] = useState(0);

  useEffect(()=>{
    
  },[])
  return (
    <>
        <Head>
            <title>Jobs | Real Fast</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container}>
            <div className="p-3 border border-gray-300 rounded py-8">
                <div className="flex flex-row justify-between mb-5 font-bold text-lg">
                    <p>Job Title</p>
                    <p>Salary: NGN1000000</p>
                </div>

                <div className="mb-8">
                    This role bridges the creative and technical aspects of project delivery- you must design and implement the user interface and engineer the experience of every site/software being put out by the business. <br /> <br />
                        You are expected to integrate front-end and server-side technologies and merge the technical architecture with creative designs and art direction. To achieve this integrated approach, you must have a fundamental understanding of the creative aesthetic while implementing technically across various platforms and frameworks and participate in business development, project planning, and knowledge leadership
                </div>
                <Link href="#" className="bg-indigo-800 text-white text-lg py-4 px-6 font-bold">JOB DETAILS</Link>
            </div>
        </main>
    </>
  )
}

const styles={
  container:'w-full px-16 py-8',
  
}